---
- name: "Prepare"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  vars:
    test_file: "test_file_00001.sh"
    test_archive: "test_file_00001.sh.tgz"
    test_target: "{{ test_path }}/bkp_archive_provision_tgz_test_target"
  tasks:
    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Deploy required packages"
      vars:
        bkp_archive:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "bkp_archive"

    - name: "Create test destination"
      ansible.builtin.file:
        state: "directory"
        mode: "0700"
        path: "{{ test_target }}"

    - name: "Create test content"
      ansible.builtin.lineinfile:
        create: true
        line: "echo 'this is a test file'"
        mode: "0644"
        path: "{{ test_path + '/' + test_file }}"
        state: "present"

    - name: "Create test archive"
      ansible.builtin.command:
        chdir: "{{ test_path }}"
        argv:
          - "tar"
          - "zcf"
          - "{{ test_path + '/' + test_archive }}"
          - "./{{ test_file }}"
      register: result
      changed_when:
        - result['rc'] == 0

    - name: "Discover archive file"
      ansible.builtin.stat:
        get_checksum: false
        follow: false
        get_mime: false
        get_attributes: false
        path: "{{ test_path + '/' + test_archive }}"
      register: test_archive_stats

    - name: "Verify the archive was created ({{ test_path + '/' + test_archive }})"
      ansible.builtin.assert:
        that:
          - test_archive_stats['stat']['exists']
...
