---
- name: "Verify"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "bkp_archive"

    - name: "Core variables are set"
      ansible.builtin.assert:
        that:
          - bkp_archive_base is defined
          - bkp_archive_packages is defined
...
