---
- name: "Backup / RClone / Server / Deploy / Package / Provision application"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ bkp_rclone_server_application }}"
    sys_package_profiles: "{{ bkp_rclone_server_profiles }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
