---
- name: "Backup / RClone / Server / Initialize"
  ansible.builtin.include_tasks:
    file: "bkp_rclone_server_initialize.yml"

- name: "Backup / RClone / Server / Deploy"
  ansible.builtin.include_tasks:
    file: "bkp_rclone_server_deploy.yml"
  when:
    - "'deploy' in bkp_rclone_server"
    - bkp_rclone_server['deploy']

- name: "Backup / RClone / Server / Finalize"
  ansible.builtin.include_tasks:
    file: "bkp_rclone_server_finalize.yml"
...
