---
- name: "Backup / Archive / Prerequisite / Prepare package managers"
  vars:
    sys_repository:
      prepare: true
      deploy: true
      setup: true
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_repository"
...
