---
- name: "Backup / Restic / Initialize"
  ansible.builtin.include_tasks:
    file: "bkp_restic_initialize.yml"

- name: "Backup / Restic / Deploy"
  ansible.builtin.include_tasks:
    file: "bkp_restic_deploy.yml"
  when:
    - "'deploy' in bkp_restic"
    - bkp_restic['deploy']

- name: "Backup / Restic / Finalize"
  ansible.builtin.include_tasks:
    file: "bkp_restic_finalize.yml"
...
