---
- name: "Backup / Archive / Usage example"
  hosts: "localhost"
  gather_facts: true
  vars:
    test_file: "terraform_1.1.2_linux_amd64.zip"
    test_path_download: "/tmp/test_path_download64"
    test_path_open: "/tmp/test_path_open64"

  pre_tasks:
    - name: "Create test paths"
      ansible.builtin.file:
        state: "directory"
        mode: "0700"
        path: "{{ item }}"
      loop:
        - "{{ test_path_download }}"
        - "{{ test_path_open }}"

    - name: "Download test file"
      ansible.builtin.get_url:
        url: "https://releases.hashicorp.com/terraform/1.1.2/{{ test_file }}"
        dest: "{{ test_path_download }}"

  tasks:
    - name: "Example: Extract the terraform CLI from the compressed file archive"
      vars:
        bkp_archive:
          resolve_prereq: true
          deploy: true
          provision: true
        bkp_archive_files:
          - archive:
              path: "{{ test_path_download }}"
              file: "{{ test_file }}"
              keep: false
            content:
              path: "{{ test_path_open }}"
              name: "terraform-cli"
      ansible.builtin.include_role:
        name: "serdigital64.backup.bkp_archive"
...
