---
- name: "Verify"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Discover packages"
      ansible.builtin.package_facts:
        manager: "auto"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "bkp_rclone_server"

    - name: "Verify required packages are deployed (package: {{ item }})"
      ansible.builtin.assert:
        that:
          - item in ansible_facts['packages']
      loop:
        - "{{
            bkp_rclone_server_profiles[
              bkp_rclone_server_application['type']
            ][
              bkp_rclone_server_application['version']
            ]['packages'][0]['name']
          }}"
...
